import { readFile, readdir, mkdir, writeFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { canonical, officialResult, sha256, type Snapshot } from '../src/core.ts';
import { fit, usable, walkForward, type Example } from '../src/learning.ts';

const dataDir=process.argv[2],outputDir=process.argv[3];
if(!dataDir || !outputDir)throw Error('Usage: node scripts/train.ts DATA_DIR OUTPUT_DIR');
const examples:Example[]=[],excluded:unknown[]=[],eligibleByRace=new Set<string>();
for(const name of (await readdir(resolve(dataDir))).filter(n=>/^\d{4}-\d{2}-\d{2}\.json$/.test(n)).sort()) {
  const data=JSON.parse(await readFile(join(dataDir,name),'utf8'));
  const observations:Snapshot[]=data.observations;
  for(const race of new Set(observations.map(s=>s.race_id))) {
    const all=observations.filter(s=>s.race_id===race);
    const earliestStart=Math.min(...all.map(s=>Date.parse(s.start_at)).filter(Number.isFinite));
    // Fixed decision at T-5; use the most recent observation, even if it abstains.
    const window=all.filter(s=>Date.parse(s.observed_at)<=earliestStart-5*60_000 && Date.parse(s.observed_at)>=earliestStart-17*60_000);
    const snapshot=window.sort((a,b)=>b.observed_at.localeCompare(a.observed_at))[0];
    if(!snapshot){excluded.push({race,reason:'NO_OBSERVATION_IN_T5_WINDOW'});continue;}
    const labels=[];
    for(const row of data.results) {
      if(await sha256(row.payload_json)!==row.payload_hash)throw Error('RESULT_HASH_MISMATCH');
      const payload=JSON.parse(row.payload_json);
      if(payload.result.race_id!==race)continue;
      const corrected=officialResult({race_id:race,date:snapshot.race_date,meeting:0,number:0,hippodrome:'',start_at:snapshot.start_at,
        raw:payload.source.course,meeting_raw:{}});
      if(corrected)labels.push({result:corrected,observed_at:row.observed_at});
    }
    const latest=labels.sort((a,b)=>b.observed_at.localeCompare(a.observed_at))[0];
    if(!latest){excluded.push({race,reason:'NO_RESULT'});continue;}
    const example:Example={snapshot,observation_id:await sha256(canonical(snapshot)),result:latest.result,result_observed_at:latest.observed_at};
    if(!usable(example)){excluded.push({race,reason:'UNUSABLE_OR_ABSTAINING',reasons:snapshot.reasons});continue;}
    if(eligibleByRace.has(race))throw Error('DUPLICATE_RACE');eligibleByRace.add(race);examples.push(example);
  }
}
const trainedAt=new Date().toISOString(),model=await fit(examples,trainedAt),evaluation=await walkForward(examples);
const report={created_at:trainedAt,decision_protocol:'T_MINUS_5_MINUTES_LAST_OBSERVATION_MAX_AGE_12_MINUTES',
  interpretation:'Retrospective chronological pilot; not an independent prospective validation. No tuning on test outcomes.',
  model,excluded,examples:examples.map(e=>({race_id:e.snapshot.race_id,observation_id:e.observation_id,observed_at:e.snapshot.observed_at,
    result_observed_at:e.result_observed_at})),evaluation};
await mkdir(resolve(outputDir),{recursive:true});
await writeFile(join(outputDir,'model.json'),JSON.stringify(model,null,2));
await writeFile(join(outputDir,'evaluation.json'),JSON.stringify(report,null,2));
await writeFile(join(outputDir,'model.ts'),`// Generated by scripts/train.ts. Experimental; never a calibrated probability guarantee.\nimport type { Model } from './selector.ts';\nexport const ACTIVE_MODEL = ${JSON.stringify(model,null,2)} satisfies Model;\n`);
console.log(JSON.stringify({model_id:model.id,training_races:model.training_races,coefficients:model.coefficients,
  tested_races:evaluation.rows.length,rows:evaluation.rows.map(r=>({race_id:r.race_id,bases3:r.proposal.bases3,bases4:r.proposal.bases4,
    all3:r.all3,all4:r.all4,moteur3:r.moteur3,market3:r.market3})),excluded}));
