export function dashboard(secureHeaders:Record<string,string>):Response {
  const nonce=crypto.randomUUID();
  const html=String.raw`<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Elite Turf — Atelier des bases</title><style nonce="${nonce}">
:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#101b21;color:#e9f2ef}body{max-width:1100px;margin:40px auto;padding:0 20px}h1{font-size:32px;margin-bottom:8px}.muted{color:#a9bcb5}header{border-bottom:1px solid #31443e;padding-bottom:18px}main{display:grid;gap:20px;margin-top:24px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.card,section{background:#192a30;border:1px solid #31443e;border-radius:12px;padding:20px}.value,.bases{font-size:30px;color:#9bd8b1}button,a{color:#b7e9c6}button{background:#244e3b;border:1px solid #4e805e;padding:12px;border-radius:6px;cursor:pointer}button:disabled{opacity:.5}table{width:100%;border-collapse:collapse;font-size:14px}td,th{text-align:left;padding:12px 6px;border-bottom:1px solid #31443e}pre{white-space:pre-wrap;font-size:13px}.warn{color:#f1c887}.wide{overflow-x:auto}.proposal{padding:14px 0;border-bottom:1px solid #31443e}@media(max-width:650px){.cards{grid-template-columns:1fr}h1{font-size:27px}}
</style><header><p class="muted">ELITE TURF · ESPACE PRIVÉ</p><h1>Atelier des bases Quinté+</h1><p>Phase 2 — Sélecteur expérimental</p><p class="muted">Moteur et Marché observés en lecture seule. Radar : branchement ultérieur.</p></header>
<main><div class="cards"><div class="card">Photographies conservées<div id="observations" class="value">—</div></div><div class="card">Photographies admissibles<div id="eligible" class="value">—</div></div><div class="card">Courses distinctes admissibles<div id="courses" class="value">—</div></div></div>
<section><h2>Les bases du moment</h2><p class="warn">Essai privé : performances encore à confirmer. Ces bases ne sont pas validées pour les abonnés.</p><p id="model" class="muted"></p><div id="proposals">Chargement…</div><p class="muted">Trois chevaux parmi les huit du Moteur. Une quatrième base apparaît seulement si les critères supplémentaires sont réunis. Les propositions expirées sont retirées de cet affichage.</p><button id="collect">Actualiser la collecte</button> <button id="refresh">Recharger l’état</button><p id="message" role="status"></p><a id="export">Télécharger les observations et bases du jour</a></section>
<section class="wide"><h2>Suivi des bases réellement émises</h2><p id="scorecard"></p><p class="muted">Une seule référence par course : dernière proposition disponible à cinq minutes du départ, avec une observation de moins de douze minutes. Seules les arrivées définitives et les non-partants vérifiés permettent de compter un résultat.</p><table><thead><tr><th>Course</th><th>Bases de référence</th><th>Arrivée</th><th>Résultat</th></tr></thead><tbody id="history"></tbody></table></section>
<section class="wide"><h2>Dernière observation par course</h2><table><thead><tr><th>Course</th><th>Édition / réception UTC</th><th>Les huit du Moteur</th><th>Qualification</th></tr></thead><tbody id="races"></tbody></table></section>
<section><h2>Passages du collecteur</h2><pre id="runs">Chargement…</pre><p class="muted">Ce service possède son stockage et son exécution. Modèle figé pour mesurer les prochaines courses ; aucun apprentissage automatique en arrière-plan.</p></section></main>
<script nonce="${nonce}">
const byId=id=>document.getElementById(id);
const labels={CANCELLED:'Course annulée : non comptée',NO_PROPOSAL:'Pas encore de proposition',EXPIRED:'Observation trop ancienne',SOURCE_REPLACED:'Nouvelle observation en attente de calcul',INPUT_NOT_ELIGIBLE:'Données non admissibles',RACE_STARTED_OR_CLOSING:'Course commencée ou départ imminent',NO_REFERENCE:'Pas de proposition admissible à T−5',ABSTAIN:'Abstention',AWAITING_DEFINITIVE_RESULT:'Arrivée définitive attendue',NON_STARTERS_UNVERIFIED:'Non-partants à vérifier',SELECTED_NON_STARTER:'Base non partante : course non comptée',REFERENCE_NOT_FROZEN:'Référence fixée à T−5',TRAINING_LEAKAGE:'Course exclue de la validation'};
const label=x=>labels[x]||x;
function row(id,values){const tr=document.createElement('tr');for(const text of values){const td=document.createElement('td');td.textContent=text;tr.append(td)}byId(id).append(tr)}
function paragraph(parent,text,cls){const p=document.createElement('p');p.textContent=text;if(cls)p.className=cls;parent.append(p)}
async function refresh(){try{
 const r=await fetch('/api/status');if(!r.ok)throw Error('Accès indisponible');const d=await r.json();
 for(const [id,key]of [['observations','observations'],['eligible','eligible'],['courses','qualified_races']])byId(id).textContent=d.totals[key]||0;
 byId('model').textContent=d.model?'Modèle pilote entraîné sur '+d.model.training_races+' courses. Version '+d.model.id+'.':'Sélecteur désactivé.';
 byId('races').replaceChildren();byId('proposals').replaceChildren();let future=0;
 for(const s of d.latest){row('races',[s.race_id,s.edition+' / '+s.observed_at,s.selection8.join(' · '),s.eligible?'Admissible':s.reasons.join(', ')]);
  if(Date.parse(s.start_at)>Date.now()){future++;const box=document.createElement('div');box.className='proposal';paragraph(box,s.race_id);const p=s.proposal;
   if(p.status==='EXPERIMENTAL'){paragraph(box,'3 bases : '+p.bases3.join(' · '),'bases');paragraph(box,p.bases4.length?'4 bases : '+p.bases4.join(' · '):'Quatrième base non retenue.');paragraph(box,'Calcul : '+p.created_at+' · valable jusqu’à '+p.valid_until+' (UTC)','muted')}
   else paragraph(box,label(p.reason),'warn');byId('proposals').append(box)}
 }
 if(!future)paragraph(byId('proposals'),'Aucune course à venir dans les dernières observations.');
 const card=d.prospective.summary;byId('scorecard').textContent='Sur les 30 derniers jours : '+card.triples_success+' / '+card.triples_scored+' trios complets ; '+card.quartets_success+' / '+card.quartets_scored+' quatuors complets. '+card.abstentions+' abstention(s) à T−5. Comparatifs sur les courses scorées : Moteur '+(card.moteur3_success||0)+' / '+(card.moteur3_scored||0)+' ; Marché '+(card.market3_success||0)+' / '+(card.market3_scored||0)+'.';
 byId('history').replaceChildren();for(const h of d.prospective.history){const p=h.reference;let issue=label(h.outcome.status);if(h.outcome.status==='SCORED')issue='3 bases : '+(h.outcome.all3?'réussies':'incomplètes')+(h.outcome.all4===null?'':' ; 4 bases : '+(h.outcome.all4?'réussies':'incomplètes'));row('history',[h.race_id,p&&p.bases3.length?p.bases3.join(' · ')+(p.bases4.length?' / 4 : '+p.bases4.join(' · '):''):'—',h.result?h.result.ranking.slice(0,5).map(g=>g.join('=')).join(' · '):'En attente',issue])}
 byId('runs').textContent=d.runs.map(r=>{const x=JSON.parse(r.details_json);return r.started_at+' '+r.status+' — '+(x.observations||0)+' observation(s), '+(x.proposals||0)+' décision(s), '+(x.results||0)+' arrivée(s)'+(x.errors&&x.errors.length?' · '+x.errors.join(', '):'')}).join('\n');
 byId('export').href='/api/export?date='+new Date().toISOString().slice(0,10);
 }catch(e){byId('message').textContent=e.message;byId('proposals').replaceChildren();paragraph(byId('proposals'),'État indisponible : recharger avant utilisation.','warn')}}
byId('collect').onclick=async()=>{byId('collect').disabled=true;byId('message').textContent='Lecture des sources et calcul…';try{const r=await fetch('/api/collect',{method:'POST'});const d=await r.json();byId('message').textContent=d.status==='COOLDOWN'?'Une collecte a eu lieu récemment ; la prochaine est automatique.':'État : '+(d.status||d.error);await refresh()}catch{byId('message').textContent='Collecte indisponible'}finally{byId('collect').disabled=false}};byId('refresh').onclick=refresh;void refresh();setInterval(refresh,60000);
</script></html>`;
  return new Response(html,{headers:{...secureHeaders,'Content-Type':'text/html; charset=utf-8',
    'Content-Security-Policy':`default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'`}});
}
