// Generated by scripts/train.ts. Experimental; never a calibrated probability guarantee.
import type { Model } from './selector.ts';
export const ACTIVE_MODEL = {
  "schema": "elite-bases-model-v1",
  "trained_at": "2026-09-26T07:46:09.177Z",
  "training_cutoff": "2026-09-25T18:37:18.668Z",
  "feature_names": [
    "log_market",
    "moteur_correction",
    "recent_top5",
    "incident_free",
    "odds_shortening"
  ],
  "coefficients": [
    0.9939917512258603,
    0.5009565365503176,
    0.2942336253548146,
    0.2554853557644425,
    0.0972349972005054
  ],
  "training_races": 5,
  "training_ids": [
    "R1C1_21092026_LA CAPELLE",
    "R1C4_22092026_AUTEUIL",
    "R1C1_23092026_ARGENTAN",
    "R1C1_24092026_COMPIEGNE",
    "R1C4_25092026_VINCENNES"
  ],
  "dataset_sha256": "6c0c4c0bb5004bad4e4cfe016f84f59e94bb55b271525aabf7b5604e98eb682e",
  "validation": "EXPERIMENTAL_SMALL_SAMPLE",
  "method": "RIDGE_PLACKETT_LUCE",
  "regularization": 1.5,
  "id": "pl-v1-86256ab03e7e66b7a87b"
} satisfies Model;
